### ISSUE TITLE
Exercise: Module  4 / fread fwrite

### ISSUE THREAD

**Issue by jesseilev** [LaunchCodeEducation/cs50x-live#178]
One or two exercises that give them practice using the `fread` and `fwrite` functions

**Comment by ghost** [comment]
Was working on it when you posted this. I actually have a really simple idea: just redo the Restaurant Menu using fread and fwrite instead of fgets and fputs. I'll put a comparison of those functions in the write up to help students understand the differences.

**Comment by jesseilev** [comment]
Perfect!

**Comment by jesseilev** [comment]
@digshake I just noticed that (I think) we were wrong, it is easy to read one line of a file.

`fgets` will stop if it encounters a `\n` character.

http://stackoverflow.com/questions/21180248/fgets-to-read-line-by-line-in-files

This means Restaurant Menu is actually not too hard, maybe we should keep it (and additionally do the one you're working on now)?

**Comment by ghost** [comment]
Yea I had come across this as well. I have already changed the lab write up to reflect this, but I haven't committed it yet.

Sometime in the next hour or so I'll commit that as well as two more exercises: Good Burger part 2, which uses fwrite instead of fput, and Restaurant Menu part 2 which uses fread instead of fgets.

I think that section will be in pretty good shape once those changes are up.

**Comment by jesseilev** [comment]
Oops I also changed the write-up by adding a little explanation of `fgets`. Feel free to combine yours and mine however you think is best

**Comment by ghost** [comment]
I've committed the two exercises and added them to the [prep page](https://github.com/LaunchCodeEducation/cs50x-live/tree/feature/module4/calendar/cs50/unit2-advanced-c/module4/materials/class2-prep)

Some things left to think about:

Do we still want a simple file creation exercise? I think it isn't necessary, since we now have two exercises that have students creating files.

Do we still want a hex conversion exercise? I think this isn't necessary either. An exercise would be quick and simple, but I don't feel the course uses hex enough to justify it.

Do we want an `fseek` exercise? This has the strongest case for having some sort of exercise, though I'm still not entirely convinced we need it. Maybe an in class demo/video would suffice?

**Comment by jesseilev** [comment]
- simple creation. I agree, don't need it
- hex conversion, don't need it
- `fseek`, would be good to have something, doesn't matter what

What about the `feof` thing? The fact that it doesn't work as expected

**Comment by ghost** [comment]
I added an explanation of EOF in the restaurant example. Is there a time when they are expected to use `feof` specifically?

**Comment by ghost** [comment]
I just realized that my explanation of EOF is incorrect, so I have to fix that. Maybe I could fix it using `feof`? I probably won't have time to get to it until tomorrow.
